### ISSUE TITLE
Still in use? - Dual Controls

### ISSUE THREAD

**Issue by Amd3202** [3esam/Xamarin.FormsJoystick#1]
I know this has been posted a long time ago, but if anyone is still working on this it's very cool. I'm interested in using it for a "remote control" for a motorized 3d-printed toy. The challenge I'm having is getting the iOS to recognize 2 of these controls on the same page at the same time. Works great with Android. With iOS if you put 2 controls on the same page the "first" one works great but you can't move the other one at the same time. The renderers are out of my depth but I'm willing to learn... if anyone's out there looking would love any advice how to address this. Thanks!

**Comment by Amd3202** [comment]
I actually figured this out! Even after this long, most of the stuff is valid for iOS/Xamarin and works nicely with latest Xamarin.Forms. 3esam did a great job!

The main issue with dual controls on one screen was the use of (UITouch)evt.AllTouches.AnyObject;

With one control on the screen it quickly could determine if the touch was for/inside itself or return. But since Apple returns all the touches in the same object, the AnyObject wouldn't latch onto the touch that was intended for. So the drag would drag the wrong object. 

What I did was used the existing "check" to see if the touches began was inside the right location if so it's the correct touch. If not I'd try the next one. Once debug was off it worked perfectly without a stutter. Using iPhone 12 Pro. 

Another cool trick was if you line the 2 joysticks up in the middle of the screen you can use the emulator with option click to get it to click both at the same time to see them work together without having to use a real device...

Anyway, if this ever helps anyone that'd be great. And if the author ever sees this, THANKS super cool code!

**Comment by 3esam** [comment]
@Amd3202  Awesome! i'm glad you found it useful.
if you can share the code i'd be grateful, and i'll update so joystick control can support single or multiple in one screen.

**Comment by Amd3202** [comment]
Happy to do so. I haven't done a clone/push in a public git before, so I'll try to figure that out quickly. I made several changes on my side to make it work with my "style" but I'll update and send with yours. Thanks for the reply!

**Comment by 3esam** [comment]
Thanks @Amd3202 !... you can also share the code the old way, a zip file link or whatever 😎

**Comment by Amd3202** [comment]
Would really love to try to use Github, as we just use AzureDevops for work (this is fun). Any chance you can give me permissions to upload my branch? I completed the edits.

**Comment by 3esam** [comment]
i agree, Github is better... i believe you already can create a PR.
i didn't really try this before but the general idea is fork this repository(would make it upstream repo), push changes to your repo and finally create PR from your repo to this one(upstream repo).
